export { default as AppMain } from './AppMain.vue'
export { default as Sidebar } from './Sidebar/index.vue'
export { default as Navbar } from './Navbar/index.vue'
export { default as Tagsbar } from './Tagsbar/index.vue'
export { default as Theme } from './Theme/index.vue'
// export { default as Avatar } from './Avatar/index.vue'